[book]
authors = ["Allan Wintersieck", "John Berger", "Brian Schiller"]
language = "en"
multilingual = false
src = "docs"
title = "DEPT DASH™ Docs"
site-url = "/dash/"
git-repository-url = "https://github.com/deptagency/dash"
edit-url-template = "https://github.com/deptagency/dash/edit/main/docs/{path}"
