import { getEnv } from "~/config";
import { createCommercetoolsClient } from "@deptdash/commercetools";

const COMMERCETOOLS_PROJECT_KEY = getEnv("COMMERCETOOLS_PROJECT_KEY");
const COMMERCETOOLS_CLIENT_ID = getEnv("COMMERCETOOLS_CLIENT_ID");
const COMMERCETOOLS_SECRET = getEnv("COMMERCETOOLS_SECRET");
const COMMERCETOOLS_SCOPES = getEnv("COMMERCETOOLS_SCOPES");
const COMMERCETOOLS_API_URL = getEnv("COMMERCETOOLS_API_URL");
const COMMERCETOOLS_AUTH_URL = getEnv("COMMERCETOOLS_AUTH_URL");

export const requestBuilder = createCommercetoolsClient(
  COMMERCETOOLS_PROJECT_KEY,
  COMMERCETOOLS_CLIENT_ID,
  COMMERCETOOLS_SECRET,
  COMMERCETOOLS_SCOPES,
  COMMERCETOOLS_API_URL,
  COMMERCETOOLS_AUTH_URL
);
