import { getEnv } from "~/config";
import { createAuthClient } from "@deptdash/commercetools";

const COMMERCETOOLS_PROJECT_KEY = getEnv("COMMERCETOOLS_PROJECT_KEY");
const COMMERCETOOLS_AUTH_URL = getEnv("COMMERCETOOLS_AUTH_URL");
const COMMERCETOOLS_CLIENT_ID = getEnv("COMMERCETOOLS_WEB_CLIENT_ID");
const COMMERCETOOLS_SECRET = getEnv("COMMERCETOOLS_WEB_SECRET");
const COMMERCETOOLS_SCOPES = getEnv("COMMERCETOOLS_WEB_SCOPES");

export const authClient = createAuthClient(
  COMMERCETOOLS_PROJECT_KEY,
  COMMERCETOOLS_AUTH_URL,
  COMMERCETOOLS_CLIENT_ID,
  COMMERCETOOLS_SECRET,
  COMMERCETOOLS_SCOPES
);
